data:
  categorical_features: ['workclass', 'education', 'marital-status', 
                     'occupation', 'relationship', 'race', 'sex', 'native-country']
  numerical_features: ['age', 'fnlgt', 'education-num', 'capital-gain','capital-loss', 'hours-per-week']
  input_path: data/
  train_test_split: 0.20

model:
  max_depth: 5
  imbalance: True